

services:
  web:
    build: .
    container_name: django_app
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - redis_broker

  redis_broker:
    image: "redis:latest"
    container_name: redis_broker
    ports:
      - "6379:6379"

  celery_worker:
    build: .
    command: celery -A email_project worker --loglevel=info
    depends_on:
      - redis_broker

  celery_beat:
    build: .
    command: celery -A email_project beat --loglevel=info
    depends_on:
      - redis_broker

  flower:
    image: mher/flower
    command: ["celery", "flower"]
    ports:
      - "5555:5555"
    environment:
      - CELERY_BROKER_URL=redis://redis_broker:6379/0
    depends_on:
      - redis_broker
      - celery_worker
